baseURL = "https://jean-golding-institute.github.io/maps/"
languageCode = "en-us"
title = "MAPS"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Rob Arbon"
    description = "mapping the analytic pathways of a crowd-sourced data analysis"
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 2
# 
# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3


